using MediatR;
using SportAcademy.Application.Common.Result;

namespace SportAcademy.Application.Commands.AuthCommands.ResetPassword;

// Public, unauthenticated: consumes the token generated by SendOwnerPasswordResetLinkCommand
// (or any future flow reusing the same token-generation split) after the user follows the
// emailed link.
public record ResetPasswordCommand(Guid UserId, string Token, string NewPassword) : IRequest<Result<bool>>;
